<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-Q0E3SEM" name="com.v1.sm.testcases.ValidateAboutusTest" tests="1" failures="1" timestamp="20 Jun 2019 07:48:59 GMT" time="29.962" errors="0">
  <testcase name="ValidateAboutusTest" time="29.962" classname="com.v1.sm.testcases.ValidateAboutusTest">
    <failure type="java.lang.AssertionError" message="Failing the aboutus Test">
      <![CDATA[java.lang.AssertionError: Failing the aboutus Test
at org.testng.Assert.fail(Assert.java:96)
at com.v1.sm.testcases.ValidateAboutusTest.ValidateAboutusTest(ValidateAboutusTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- ValidateAboutusTest -->
</testsuite> <!-- com.v1.sm.testcases.ValidateAboutusTest -->
